steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: [ 'install' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/wezara/volumeanalyzer', '.']
    timeout: 500s
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-central2-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
options:
  machineType: 'N1_HIGHCPU_8'
timeout: 660s
